-- DEPRECATED: Do not disable RLS. That exposes tables via the Supabase anon key.
--
-- If inbox sync fails with RLS errors on Railway, confirm:
--   SUPABASE_SERVICE_ROLE_KEY is set (not the anon key).
--
-- To apply the lockdown migration on an existing project, run:
--   backend/db/migrations/010_enable_rls_lockdown.sql
